# Generated by Django 2.2.10 on 2021-03-25 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiverName', models.CharField(max_length=100)),
                ('receiverPhone', models.CharField(max_length=100)),
                ('destinationAddress', models.CharField(max_length=100)),
                ('destinationCounty', models.CharField(max_length=100)),
                ('dateSend', models.CharField(max_length=100)),
                ('dateExpected', models.CharField(max_length=100)),
                ('labelName', models.CharField(max_length=100)),
                ('Quantity', models.CharField(max_length=100)),
                ('senderName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('homeCounty', models.CharField(max_length=100)),
                ('homeTown', models.CharField(max_length=100)),
                ('currentCounty', models.CharField(max_length=100)),
                ('currentTown', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
