# Generated by Django 2.2.10 on 2021-05-17 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServerSide', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerName', models.CharField(max_length=100)),
                ('customerPhone', models.CharField(max_length=100)),
                ('customerId', models.CharField(max_length=100)),
                ('customerStartLoc', models.CharField(max_length=100)),
                ('customerDestinationLoc', models.CharField(max_length=100)),
                ('stationStaffId', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(max_length=100)),
                ('itemType', models.CharField(max_length=100)),
                ('Quantity', models.CharField(max_length=100)),
                ('originStation', models.CharField(max_length=100)),
                ('originCounty', models.CharField(max_length=100)),
                ('receiverName', models.CharField(max_length=100)),
                ('receiverPhone', models.CharField(max_length=100)),
                ('destinationAddress', models.CharField(max_length=100)),
                ('destinationCounty', models.CharField(max_length=100)),
                ('dateSend', models.CharField(max_length=100)),
                ('dateExpected', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerPhone', models.CharField(max_length=100)),
                ('paymentAmount', models.CharField(max_length=100)),
                ('paymentMeans', models.EmailField(max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stationName', models.CharField(max_length=100)),
                ('stationLocation', models.CharField(max_length=100)),
                ('stationStaffId', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Courier',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
